### ISSUE TITLE
using proper set of offset for calculating L_seg and L_angle losses

### ISSUE THREAD

**Issue by nagitam** [zorzi-s/PolyWorldPretrainedNetwork#13]
Thanks for the very interesting work. At the end of section 4, you have mentioned 
`Since the NMS block is not differentiable, the only way
for the network to minimize L_seg and L_angle is to generate
a proper set of offsets t for Equation 6.`

Can you please elaborate more on this? Does this mean you are not using the `t_i` values generated by the attentional gnn? Do you propagate this loss through the score matrix generated by the optimal connection network?

**Comment by zorzi-s** [comment]
Hi @nagitam,

thank you for the interest on our work!

The offsets $t_i$ are used to refine the vertex positions minimizing $L_{seg}$ and $L_{angle}$.
The final positions are given with equation (6): $\hat{p}_i = p_i + \gamma \cdot t_i$. Since the NMS layer, that produces the initial coordinates $p_i$, is not differentiable, the network can just learn to modify the positions through the offsets $t_i$. The refinement losses do not affect vertex detection map and NMS, and therefore, the coordinates $p_i$.

**Comment by nagitam** [comment]
Thank you @zorzi-s 
Your explanation makes sense 👍
